### ISSUE TITLE
Raw single-viewpoint drone images

### ISSUE THREAD

**Issue by russelldj** [gyrrei/ReforesTree#4]
Hi all,

I've really enjoyed working with this dataset. For some of my current work, it would be helpful to have the raw images which were collected by the drone and--ideally--the location of each camera as optimized by structure from motion. As far as I can tell, only the orthomosaic is provided here. Alternatively, if you have the geotagged images, I could re-run structure from motion myself.

Is this something that I missed or that you'd be willing to provide?

Best,
David

**Comment by bw4sz** [comment]
@russelldj did you ever hear back on this?

**Comment by russelldj** [comment]
@bw4sz Unfortunately I have not. I'm still interested in the data though.

**Comment by gyrrei** [comment]
[Drone Mapping for WWF Panda Labs in Ecuador.pdf](https://github.com/gyrrei/ReforesTree/files/13313075/Drone.Mapping.for.WWF.Panda.Labs.in.Ecuador.pdf)

Thanks for the issue, @russelldj! Unfortunately, I never had access to the original drone data. The WWF provided this information about the data collection and drone images.
