### ISSUE TITLE
Confirm annotation overlap? Are all trees annotated?

### ISSUE THREAD

**Issue by bw4sz** [gyrrei/ReforesTree#5]
I am the mantainer of the DeepForest (https://deepforest.readthedocs.io/en/latest/) tree detection backbone. I'd like to add these annotations as pretraining for our algorithm. I downloaded the dataset, loaded mapping/final_dataset.csv and overlaid them on the matching names in the /tiles directory. I can't tell if the annotations were correctly read in. In orange are the ReForestTree ground truth, in blue are DeepForest predictions, they can be ignored, except to show that there are unlabeled trees in the images that lack annotations? Were all trees intended to be annotated? Let me know if I'm misunderstanding how to use the dataset.

<img width="554" alt="Screenshot 2023-11-06 at 1 33 40 PM" src="https://github.com/gyrrei/ReforesTree/assets/1208492/5618dc42-e0cc-451a-89cf-7b75b9bd276d">

**Comment by AlexTo** [comment]
@bw4sz I have similar observation when uploading the images in `tiles_400_400` and the annotation `all.json` to CVAT. The annotation in `all.json` is essentially the same as the csv file, except being in COCO format.

In most images, I find that the annotations are not that clean and usually not all trees are annotated. Perhaps, I'm missing something here?

<img width="739" alt="image" src="https://github.com/gyrrei/ReforesTree/assets/296212/9e3ae62b-e5bd-4c90-b4d9-7f73d48ae31c">

**Comment by gyrrei** [comment]
@bw4sz thank you for raising the issue. As the boxes were manually cleaned, we have previously identified missing boxes for some trees. 

We believe the core issue causing this is a potentially wrong assumption about the boundaries for the collected ground truth data. Please take a look at the documentation from https://github.com/TimEngelmann/ai4est/.

**Comment by AlexTo** [comment]
@gyrrei could you elaborate further, so the Reforestree does have some issues and we should look at `ai4est` instead right?
